[2025-07-06 20:55:53,049] WARNING delete_paciente() L242  Erro ao deletar pessoa 'PessoaInexistente', Pessoa não encontrado na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L242 
[2025-07-06 20:55:53,116] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 20:55:53,116] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 20:56:19,399] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 20:56:19,400] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 20:56:19,423] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 20:56:19,423] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 20:56:19,447] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 20:56:19,447] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 20:56:19,455] WARNING get_pessoa() L203  Erro ao buscar produto 'PessoaInexistente', Pessoa PessoaInexistente não encontrado na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L203 
[2025-07-06 20:56:19,550] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 20:56:19,551] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 20:56:19,562] WARNING delete_paciente() L242  Erro ao deletar pessoa 'PessoaInexistente', Pessoa não encontrado na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L242 
[2025-07-06 20:56:19,617] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 20:56:19,617] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 20:56:57,528] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 20:56:57,530] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 20:56:57,551] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 20:56:57,551] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 20:56:57,577] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 20:56:57,577] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 20:56:57,585] WARNING get_pessoa() L203  Erro ao buscar produto 'PessoaInexistente', Pessoa PessoaInexistente não encontrado na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L203 
[2025-07-06 20:56:57,680] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 20:56:57,682] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 20:56:57,695] WARNING delete_paciente() L242  Erro ao deletar pessoa 'PessoaInexistente', Pessoa não encontrado na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L242 
[2025-07-06 20:57:09,184] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 20:57:09,186] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 20:57:09,210] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 20:57:09,211] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 20:57:09,236] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 20:57:09,236] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 20:57:09,244] WARNING get_pessoa() L203  Erro ao buscar produto 'PessoaInexistente', Pessoa PessoaInexistente não encontrado na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L203 
[2025-07-06 20:57:09,349] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 20:57:09,349] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 20:57:09,360] WARNING delete_paciente() L242  Erro ao deletar pessoa 'PessoaInexistente', Pessoa não encontrado na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L242 
[2025-07-06 20:57:09,416] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 20:57:09,417] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 20:59:40,591] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 20:59:40,591] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 20:59:40,627] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 20:59:40,628] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 20:59:40,663] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 20:59:40,668] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 20:59:40,681] WARNING get_pessoa() L203  Erro ao buscar produto 'PessoaInexistente', Pessoa PessoaInexistente não encontrado na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L203 
[2025-07-06 20:59:40,810] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 20:59:40,811] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 20:59:40,824] WARNING delete_paciente() L242  Erro ao deletar pessoa 'PessoaInexistente', Pessoa não encontrado na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L242 
[2025-07-06 20:59:40,922] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
