[2025-07-06 20:59:40,922] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 21:00:33,088] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 21:00:33,089] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 21:00:33,108] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 21:00:33,108] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 21:00:33,138] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 21:00:33,138] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 21:00:33,147] WARNING get_pessoa() L203  Erro ao buscar produto 'PessoaInexistente', Pessoa PessoaInexistente não encontrado na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L203 
[2025-07-06 21:00:33,245] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 21:00:33,246] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 21:00:33,260] WARNING delete_paciente() L242  Erro ao deletar pessoa 'PessoaInexistente', Pessoa não encontrado na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L242 
[2025-07-06 21:00:33,334] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 21:00:33,334] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 21:02:15,168] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 21:02:15,170] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 21:02:15,203] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 21:02:15,205] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 21:02:15,243] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 21:02:15,243] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 21:02:15,257] WARNING get_pessoa() L203  Erro ao buscar produto 'PessoaInexistente', Pessoa PessoaInexistente não encontrado na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L203 
[2025-07-06 21:02:15,378] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 21:02:15,378] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 21:02:15,393] WARNING delete_paciente() L242  Erro ao deletar pessoa 'PessoaInexistente', Pessoa não encontrado na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L242 
[2025-07-06 21:02:15,452] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 21:02:15,452] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 21:03:26,683] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 21:03:26,684] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 21:03:26,736] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 21:03:26,737] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 21:03:26,811] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 21:03:26,813] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 21:03:26,833] WARNING get_pessoa() L203  Erro ao buscar produto 'PessoaInexistente', Pessoa PessoaInexistente não encontrado na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L203 
[2025-07-06 21:03:26,903] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 21:03:26,903] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 21:03:26,930] WARNING delete_paciente() L242  Erro ao deletar pessoa 'PessoaInexistente', Pessoa não encontrado na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L242 
[2025-07-06 21:03:27,044] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 21:03:27,044] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 21:44:19,439] INFO _log() L97   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 21:44:19,440] INFO _log() L97   [33mPress CTRL+C to quit[0m - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 21:44:19,442] INFO _log() L97    * Restarting with stat - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 21:44:23,701] INFO _log() L97   127.0.0.1 - - [06/Jul/2025 21:44:23] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 21:44:23,866] INFO _log() L97   127.0.0.1 - - [06/Jul/2025 21:44:23] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 21:44:23,917] INFO _log() L97   127.0.0.1 - - [06/Jul/2025 21:44:23] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 21:44:24,022] INFO _log() L97   127.0.0.1 - - [06/Jul/2025 21:44:24] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 21:44:24,157] INFO _log() L97   127.0.0.1 - - [06/Jul/2025 21:44:24] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 21:44:24,198] INFO _log() L97   127.0.0.1 - - [06/Jul/2025 21:44:24] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
